### PR TITLE
Solved Issue#20

### PR DESCRIPTION
**Pull request by singhaditya28**
#20

### CODE REVIEW

**Comment by naazkakria** [comment]
i can merge it but, can't accept it under hacktoberfest :(

**Comment by singhaditya28** [comment]
Actually I am a newbie. Hacktoberfest website told me that I can get selected by starting with the documentation itself. Please accept it.

**Comment by naazkakria** [comment]
no worries you can improve  this readme take an example from https://github.com/IoT-Buzz/IoT/blob/main/README.md

**Comment by ravinder-chadha** [comment]
Closing this PR as it has merge conflicts as well as it is not up to the mark.

**Pull request closed without merging**
