### PR TITLE
Added a RL project I made

### PR DESCRIPTION
**Pull request by 19-ade**
Hey!! It's me again . This is a reinforcement learning project I made . I applied a Deep Q Network to help the agent to play the google chrome dino game .

I closed the PR for the hardware project because my friends and I made it together and it would be unfair to take the credit myself for the PR since my friends are not that active on github . However if you want to discuss about it you can always pm in discord . 
id : anwesan_de#3193

### CODE REVIEW

**Comment by naazkakria** [comment]
okay, but please shorten the folder name and make readme short and crisp :)

**Comment by 19-ade** [comment]
Sure!!!!

**Comment by 19-ade** [comment]
I'm unable to change the folder name . Can you please help me out here ?? Thank you so much for this opportunity .

**Comment by hardikchopra242** [comment]
@19-ade you can try to make another pull request and closing this one. Make the required changes and make another PR. Let me know if you have any other queries.

**Comment by 19-ade** [comment]
Alright !! Thank you .

**Pull request closed without merging**
