### PR TITLE
Added a new python script

### PR DESCRIPTION
**Pull request by RKNpy**
Added new python script to count files present in a directory.

### CODE REVIEW

**Review by hardikchopra242 — CHANGES_REQUESTED** [review]
Correct the typo in FIle_counter/filecounter.txt (wether -> whether)

**Comment by RKNpy** [comment]
> Correct the typo in FIle_counter/filecounter.txt (wether -> whether)

Fixed :)

**Review by hardikchopra242 — APPROVED** [review]

**Comment by naazkakria** [comment]
@RKNpy  please add a screenshot of output in readme if possible

**Comment by RKNpy** [comment]
> @RKNpy please add a screenshot of output in readme if possible

ok sure.

**Comment by naazkakria** [comment]
@RKNpy I will suggest you make one new PR, with some  @files as we will count that PR in hacktoberfest

**Comment by RKNpy** [comment]
> @RKNpy I will suggest you make one new PR, with some @files as we will count that PR in hacktoberfest

sure I will try

**Comment by RKNpy** [comment]
Added a new python project (I forgot to change the branch...) here only 
will be adding new commands to `Cutify Discord Bot` soon

**Pull request merged**
