### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pranjalmishra30**
Fixes https://github.com/IoT-Buzz/IoT/issues/18  
- Updated the README for the hardware directory.
- Added a brief intro
- Added table of contents

### CODE REVIEW

**Comment by hardikchopra242** [comment]
The table should look like [this](https://github.com/IoT-Buzz/IoT/blob/main/IoT-For-Beginners/Lesson-3/5.%20Resources.md). 
Please make the required changes.You may refer [this](https://dev.to/hardikchopra242/do-you-know-markdown-2d2p#tables)

**Review by hardikchopra242 — CHANGES_REQUESTED** [review]
Make a table in place of the bullets.

**Comment by Pranjalmishra30** [comment]
Added the table as requested. Please do let me know if there needs to be any other changes.
Thanks :)

**Review by hardikchopra242 — APPROVED** [review]

**Comment by naazkakria** [comment]
Thanks for contributing :)

**Pull request merged**
