### PR TITLE
Please Try it

### PR DESCRIPTION
**Pull request by nayan2306**
If any changes required tell me

### CODE REVIEW

**Comment by naazkakria** [comment]
hey @nayan2306  it would be great if you add readme(atleast 2-3 lines) explaining your code

**Comment by nayan2306** [comment]
Okay I will add it .
I have a one doubt I have created one AIR canvas using python can I update that code in new file ?

**Comment by naazkakria** [comment]
yeah sure, even you can send that project in 2nd PR :)

**Comment by nayan2306** [comment]
Done

**Comment by naazkakria** [comment]
thanks for contribution  :)

**Comment by naazkakria** [comment]
thanks for contribution

**Pull request merged**
